### ISSUE TITLE
 ips is not iterable issue

### ISSUE THREAD

**Issue by supanut1911** [dollarsignteam/nestjs-jaeger-tracing#8]
I following at TracingModule.forRoot at module.ts but when I call API it's throw error like this

TypeError: ips is not iterable
    at TracingInterceptor.intercept (.../node_modules/@dollarsign/nestjs-jaeger-tracing/dist/interceptors/tracing.interceptor.js:75:69)
    at .../node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
    at InterceptorsConsumer.intercept (...node_modules/@nestjs/core/interceptors/interceptors-consumer.js:25:24)
    at .../node_modules/@nestjs/core/router/router-execution-context.js:46:60
    at Object.<anonymous> (.../node_modules/@nestjs/core/router/router-proxy.js:9:23)
    at preHandlerCallback (.../node_modules/fastify/lib/handleRequest.js:124:28)
    at preValidationCallback (.../node_modules/fastify/lib/handleRequest.js:107:5)
    at handler (.../node_modules/fastify/lib/handleRequest.js:70:7)
    at handleRequest (.../node_modules/fastify/lib/handleRequest.js:18:5)
    at runPreParsing (.../node_modules/fastify/lib/route.js:391:5)

**Comment by anwam** [comment]
can you provide us a sample or minimal reproduction
